language: python
branches:
  only:
    - master
install:
    - git config --global user.email "lumol-bot@lumol.org"
    - git config --global user.name "Travis-CI autobuild"
    - git config --global push.default simple
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script:
    # Remove previous files
    - ls -Isrc -IREADME.md -ILICENSE -ICNAME | xargs rm -rf
    - ls
    - pip install cactus pygments
    - cd src
    - cactus build
    - cd ..
    - mv src/.build/* .
    - git status
    - git add .
    - git commit --allow-empty -a -m "[AUTO-COMMIT] Build the website" -m "[ci skip]"
    - git push origin HEAD:master
